### ISSUE TITLE
更本跑步起来

### ISSUE THREAD

**Issue by wiselinpm** [WangLaoShi/HandRead#1]
Traceback (most recent call last):
  File "/Users/linxiaobin/Desktop/HandRead-master/myGUI.py", line 142, in show_camera
    roi, res, ret, self.fourier_result, self.efd_result = pic.binaryMask(frame, x0, y0, width, height)
  File "/Users/linxiaobin/Desktop/HandRead-master/picture.py", line 26, in binaryMask
    ret, fourier_result = fd.fourierDesciptor(res)
  File "/Users/linxiaobin/Desktop/HandRead-master/fourierDescriptor.py", line 14, in fourierDesciptor
    contour = find_contours(Laplacian)#提取轮廓点坐标
  File "/Users/linxiaobin/Desktop/HandRead-master/fourierDescriptor.py", line 31, in find_contours
    contour = sorted(contour, key = cv2.contourArea, reverse=False)#对一系列轮廓点坐标按它们围成的区域面积进行排序
cv2.error: OpenCV(4.6.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/shapedescr.cpp:315: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'contourArea'

**Comment by sunxian-arch** [comment]
后来解决了吗？

**Comment by the-lane** [comment]
请问后面解决了吗，我也一直有这个问题，不知道怎么解决
